<?php

        $Id_Folio = $data[0]['Id_Folio'];
        $Id_Clientes_2  = $data[0]['Clientes'];
        $Precio_millar     = $data[0]['precio_millar'];
        $Fecha             = $data[0]['Fecha'];
        $Descripcion       = $data[0]['descripcion'];
        $Medida            = $data[0]['medida'];
        $Cantidad_millares = $data[0]['cantidad_elaborar'];
        $Acabado           = $data[0]['acabados'];
        $Codigo            = $data[0]['codigo'];
        $Tratamiento       = $data[0]['tratamiento'];
        $Fecha_entrega     = $data[0]['fecha_entrega'];
        $Dibujo = $data[0]['Id_Catalogo'];
        $Salida           = $data[0]['Id_Salida_FK'];
        $Factor           = $data[0]['factor'];

        echo '<tr>';
            echo '<td style="padding: 5px;border: none;">'.$Descripcion.'</td>';
            echo '<td style="padding: 5px;border: none;">'.$Medida.'</td>';
            echo '<td style="padding: 5px;border: none;">'.$Cantidad_millares.'</td>';
            echo '<td style="padding: 5px;border: none;">'.$Acabado.'</td>';
            echo '<td class="txt-right" style="padding: 5px;border: none;">'.$Codigo.'</td>';
        echo '</tr>';
        echo '<tr>';
            echo '<td style="padding: 5px;border: none;" colspan="2"></td>';
            echo '<td style="padding: 5px;background: #C4D79B; font-weight: bold; border: none;" class="txt-center">'.$Tratamiento.'</td>';
            echo '<td style="padding: 5px;border: none;"></td>';
            echo '<td class="txt-right" style="padding: 5px;background: #FFFF00; font-weight: bold; border: none;">'.$Dibujo.'</td>';
        echo '</tr>';
        echo '<tr>';
            echo '<td style="padding: 5px;border: none;" colspan="2" class="txt-right">FECHA DE ENTREGA</td>';
            echo '<td style="padding: 5px;background: #87DEE8; font-weight: bold; border: none;">'. $Fecha_entrega.'</td>';
            echo '<td style="padding: 5px;border: none;"></td>';
            echo '<td style="padding: 5px;border: none;"></td>';
        echo '</tr>';
        echo '<tr></tr>';
        echo '<tr>';
        echo '<td  style="padding: 5px;border: none;" colspan="4" class="txt-right">SALIDA</td>';
        echo '<td class="txt-center" style="padding: 5px;background: #F2F2F2; font-weight: bold; border: none;">'. $Salida.'</td>';
        echo '</tr>';
        echo '<tr>';
            echo '<td style="padding: 5px;border: none;"></td>';
            echo '<td style="padding: 5px;border: none;" class="txt-center"></td>';
            echo '<td style="padding: 5px;border: none; background: #BFBFBF;" class="txt-center">FORMULA</td>';
            echo '<td style="padding: 5px;border: none; background: #BFBFBF;" class="txt-center">COSTO</td>';
            echo '<td style="padding: 5px;border: none; background: #BFBFBF;" class="txt-center">COSTO X</td>';
        echo '</tr>';
        echo '<tr>';
            echo '<td style="padding: 5px;border: none;"></td>';
            echo '<td style="padding: 5px;border: none; background: #A6A6A6;" class="txt-center">'.$Factor.'</td>';
            echo '<td style="padding: 5px;border: none;" class="txt-center"></td>';
            echo '<td style="padding: 5px;border: none;" class="txt-center"></td>';
            echo '<td style="padding: 5px;border: none;" class="txt-center">$ '.number_format(($Factor*1.3*26*3.4),2).'</td>';
        echo '</tr>';